# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef7efb721735ad5f49dc175eb136901411b00f0bbdedf95f0a59dbcf9176e1c819e5bbaa3d79d542ff2b9166834b0bc814c20e69717493b40aa2816a9a890351

test:
  secret_key_base: e4fc7cfbd19e121cdb9c60f027f9abc5dda22229f2a31c22b9486f9f48c0d51e63e498cf2b5a3f83953fc87f81d4eff1b362a80e30426ab1fbd3b0b9500d58d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
